version: '3.4'

networks:
  host:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - host

  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis
    networks:
      - host

  celery_worker:
    container_name: celery_worker
    build: .
    environment:
      - REDIS_BROKER=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
    command: celery -A celery_worker worker --pool=solo --loglevel=info -E
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    networks:
      - host

  flower:
    container_name: flower
    build: .
    environment:
      - REDIS_BROKER=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
    command: celery -A celery_worker flower --port=5555
    ports:
      - "5556:5555"
    networks:
      - host
    depends_on:
      - app
      - redis
      - celery_worker

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - host


  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    networks:
      - host
    ports:
      - "3000:3000"
